Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/02/2026
Var
// Seção de Declarações das variáveis 
   nome: caractere
   Primeira_nota: real
   segunda_nota: real
   terceira_nota: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite o nome: ")
   leia(nome)
   
   escreva("Digite a nota 1: ")
   leia(primeira_nota)
   
   escreva("Digite a nota 2: ")
   leia(segunda_nota)
   
   escreva("Digite a nota 2: ")
   leia(terceira_nota)




Fimalgoritmo