Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/02/2026
Var
// Seção de Declarações das variáveis 
 salario: real
 salario_minimo: real
 quantidade_salario:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 //ENTRADA
 escreva("Digite o valor do salário: ")
 leia(salario)
 
 // PROCESSAMENTO
 salario_minimo <- 1621
 quantidade_salario <-salario / salario_minimo
 
 //SAIDA
 escreval("Quantidade de salario: ", quantidade_salarios:3:1)
 
 
Fimalgoritmo